import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Pankaj',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Rawat',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: 1,
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt for men',
    },
    {
      //_id: 2,
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 10,
      description: 'High quality shirt for men',
    },
    {
      //_id: 3,
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 18,
      description: 'High quality pant for men',
    },
    {
      //_id: 4,
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 200,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 10,
      description: 'High quality pant for men',
    },
    {
      //_id: 5,
      name: 'JBL Headphone',
      slug: 'jbl-headphone',
      category: 'Headphone',
      image: '/images/p5.jpg',
      price: 599,
      countInStock: 30,
      brand: 'JBL',
      rating: 4.9,
      numReviews: 50,
      description: 'High quality headphone for music lover',
    },
    {
      //_id: 6,
      name: 'BOAT Headphone',
      slug: 'boat-headphone',
      category: 'Headphone',
      image: '/images/p6.jpg',
      price: 499,
      countInStock: 10,
      brand: 'BOAT',
      rating: 4.5,
      numReviews: 5,
      description: 'High quality headphone for music lover',
    },
    {
      //_id: 7,
      name: 'Zebronics Speaker',
      slug: 'zebronics-speaker',
      category: 'Speaker',
      image: '/images/p7.jpg',
      price: 1599,
      countInStock: 10,
      brand: 'Zebronics',
      rating: 4.1,
      numReviews: 30,
      description: 'Zebronics Speaker with 100db sound',
    },
    {
      //_id: 8,
      name: 'Mac Book Laptop',
      slug: 'mac-book-laptop',
      category: 'Mac',
      image: '/images/p8.jpg',
      price: 1999,
      countInStock: 5,
      brand: 'Mac',
      rating: 5,
      numReviews: 30,
      description: 'Solid and High performance Laptop',
    },
    {
      //_id: 9,
      name: 'Samsung NoteBook Laptop',
      slug: 'samsung-notebook-laptop',
      category: 'Laptop',
      image: '/images/p9.jpg',
      price: 899,
      countInStock: 0,
      brand: 'Samsung',
      rating: 4.6,
      numReviews: 30,
      description: 'Multitasking Laptop for rapid growth',
    },
    {
      //_id: 10,
      name: 'Iphone Pink Mobile',
      slug: 'iphone-pink-mobile',
      category: 'Mobile',
      image: '/images/p10.jpg',
      price: 599,
      countInStock: 50,
      brand: 'Iphone',
      rating: 4.9,
      numReviews: 30,
      description: 'Pink Iphone for high resolution camera and battery backup',
    },
    {
      //_id: 11,
      name: 'Iphone Blue Mobile',
      slug: 'iphone-blue-mobile',
      category: 'Mobile',
      image: '/images/p11.jpg',
      price: 599,
      countInStock: 50,
      brand: 'Iphone',
      rating: 4.9,
      numReviews: 30,
      description: 'Blue Iphone for high resolution camera and battery backup',
    },
    {
      //_id: 12,
      name: 'Iphone Green Mobile',
      slug: 'iphone-green-mobile',
      category: 'Mobile',
      image: '/images/p12.jpg',
      price: 599,
      countInStock: 50,
      brand: 'Iphone',
      rating: 4.9,
      numReviews: 30,
      description: 'Green Iphone for high resolution camera and battery backup',
    },
    {
      //_id: 13,
      name: 'Galaxy Ultra Mobile',
      slug: 'galaxy-ultra-mobile',
      category: 'Mobile',
      image: '/images/p13.jpg',
      price: 999,
      countInStock: 50,
      brand: 'Galaxy Ultra',
      rating: 4.9,
      numReviews: 30,
      description: 'Galaxy Ultra phone with touch pencile',
    },
    {
      //_id: 14,
      name: 'JBL Earbuds',
      slug: 'jbl-earbuds',
      category: 'Earbuds',
      image: '/images/p14.jpg',
      price: 299,
      countInStock: 50,
      brand: 'JBL',
      rating: 4.9,
      numReviews: 30,
      description: 'JBL Earbud with high quality noise cancellation',
    },
    {
      //_id: 15,
      name: 'Amazon Basic Earbuds',
      slug: 'amazon-basic-earbuds',
      category: 'Earbuds',
      image: '/images/p15.jpg',
      price: 199,
      countInStock: 50,
      brand: 'Amazon',
      rating: 4.5,
      numReviews: 30,
      description: 'Amazon Basic Earbuds are for basic use earbuds',
    },
    {
      //_id: 16,
      name: 'JBL Speaker',
      slug: 'jbl-speaker',
      category: 'Speaker',
      image: '/images/p16.jpg',
      price: 499,
      countInStock: 0,
      brand: 'JBL',
      rating: 4.5,
      numReviews: 30,
      description: 'JBL Speaker with 50db sound',
    },
    {
      //_id: 17,
      name: 'Tribit Speaker',
      slug: 'tribit-speaker',
      category: 'Speaker',
      image: '/images/p17.jpg',
      price: 1099,
      countInStock: 10,
      brand: 'Tribit',
      rating: 4.3,
      numReviews: 30,
      description: 'Tribit Speaker with 80db sound',
    },
  ],
};

export default data;
